# NumPy (Numeric Python) Nedir?

--> NumPy, Python'da bilimsel hesaplama için temel pakettir. Çok boyutlu bir dizi nesnesi, çeşitli türetilmiş nesneler (maskelenmiş diziler ve matrisler gibi) ve diziler üzerinde matematiksel, mantıksal, şekil işleme, sıralama, seçme, G/Ç dahil olmak üzere hızlı işlemler için çeşitli rutinler sağlayan bir Python kitaplığıdır. Ayrık Fourier dönüşümleri, temel doğrusal cebir, temel istatistiksel işlemler, rastgele simülasyon ve çok daha fazlasını yapmaya yarayan bir Python kitaplığıdır.

--> NumPy paketinin merkezinde "ndarray" nesnesi bulunur. Bu, performans için derlenmiş kodda gerçekleştirilen birçok işlemle birlikte, homojen veri türlerinin n boyutlu dizilerini kapsar. NumPy dizileri ile standart Python dizileri arasında birkaç önemli farklar vardır:

> NumPy dizileri, Python listelerinin (dinamik olarak büyüyebilen) aksine, oluşturulurken sabit bir boyuta sahiptir. Bir ndarray'in boyutunu değiştirmek, yeni bir dizi oluşturacak ve orijinali silecektir.

> NumPy dizisindeki öğelerin hepsinin aynı veri türünde olması gerekir ve bu nedenle bellekte aynı boyutta olacaktır. İstisna: bir (Python, NumPy dahil) nesne dizilerine sahip olabilir, böylece farklı büyüklükteki öğelerin dizilerine izin verilir.

> NumPy dizileri, çok sayıda veri üzerinde gelişmiş matematiksel ve diğer türdeki işlemleri kolaylaştırır. Tipik olarak, bu tür işlemler Python'un yerleşik dizileri kullanılarak mümkün olandan daha verimli ve daha az kodla yürütülür.

> Artan sayıda bilimsel ve matematiksel Python tabanlı paketler NumPy dizilerini kullanıyor; Bunlar tipik olarak Python dizisi girişini desteklese de, bu girişi işlemeden önce NumPy dizilerine dönüştürürler ve genellikle NumPy dizilerinin çıktısını alırlar. Başka bir deyişle, günümüzün bilimsel/matematiksel Python tabanlı yazılımlarının çoğunu (belki de çoğunu) verimli bir şekilde kullanmak için, yalnızca Python'un yerleşik dizi türlerini nasıl kullanacağınızı bilmek yetersizdir - ayrıca NumPy dizilerinin nasıl kullanılacağını da bilmek gerekir.

## NumPy Kütüphanesini Çağırma ve Dizi Oluşturma 

In [1]:
import numpy as np

In [2]:
vectory_empty = np.array([]) #NumPy ile boş bir dizi oluşturduk.
print(vectory_empty)

[]


In [3]:
vectory_initialized = np.array([3,4,-5,6,8]) #NumPy ile dolu bir dizi oluşturduk
print(vectory_initialized)

[ 3  4 -5  6  8]


+ NumPy ile oluşturduğumuz dizi Python'un dizisi olmamasına rağmen Python'un dizisi gibi kullanılabiliyor.

In [4]:
for i in vectory_initialized:
    print(i)

3
4
-5
6
8


## Diziye Eleman Ekleme ve Silme  

In [5]:
vector = np.array([6,4,3,9,8])

In [6]:
vector

array([6, 4, 3, 9, 8])

In [7]:
np.append(vector,11)

array([ 6,  4,  3,  9,  8, 11])

In [8]:
np.insert(vector,2,5)

array([6, 4, 5, 3, 9, 8])

In [9]:
np.delete(vector,3)

array([6, 4, 3, 8])

+ Dikkat edersek her bir işlem yeni bir dizi yaratıyor. Yani vector üzerine append, insert, delete işlemlerini uyguladığımızda Mevcut dizide işlem yapmak yerine yeni bir dizi oluşuturup yapıyor

In [10]:
vector 

array([6, 4, 3, 9, 8])

## Dizinin Türünü Gösterme  

In [11]:
vector_1 = np.array([6,2,7,3,8])
print("Tür:", vector.dtype)

Tür: int32


+ Sadece 1 tanesinin float olması, türü float olarak göstermesine neden olur

In [12]:
vector_2 = np.array([6,2,7.5,3,8]) 
print(f"Tür: {vector_2.dtype}")

Tür: float64


In [13]:
vector_3 = np.array([6,2,7,8], np.int64)
print("Tür:", vector_3.dtype)

Tür: int64


## Yuvarlama 

In [14]:
real = np.array([6.4325, 2.5436, 7.5436, 3.5432, 8.9543])

In [15]:
real

array([6.4325, 2.5436, 7.5436, 3.5432, 8.9543])

##### np.around() yuvarlama yapar (Aslında virgülden sonraki kısımları atar) 

In [16]:
rounds = np.around(real)

In [17]:
rounds

array([6., 3., 8., 4., 9.])

##### Yuvarlama yapmamız dizinin türünü değiştirmez 

In [18]:
rounds.dtype 

dtype('float64')

##### decimals parametresi ile küsüratın kaç basamağını istediğimizi belirtebiliriz 

In [19]:
rounders = np.around(real, decimals = 2)

In [20]:
rounders

array([6.43, 2.54, 7.54, 3.54, 8.95])

## Matematiksel İşlemler ve Diğer Farklı Komutlar

In [21]:
vector1 = np.array([1.1,1.2,1.3])
vector2 = np.array([2.1,2.2,2.3])

##### Toplama 

In [22]:
added = np.add(vector1, vector2)

In [23]:
added

array([3.2, 3.4, 3.6])

##### Çıkarma 

In [24]:
substracted = np.subtract(vector1, vector2)

In [25]:
substracted

array([-1., -1., -1.])

##### Çarpma 

In [26]:
multipled = np.multiply(vector1, vector2)

In [27]:
multipled

array([2.31, 2.64, 2.99])

##### Bölme 

In [28]:
divided = np.divide(vector1, vector2)

In [29]:
divided

array([0.52380952, 0.54545455, 0.56521739])

##### Kök Alma 

In [30]:
rooted = np.sqrt(vector1)

In [31]:
rooted

array([1.04880885, 1.09544512, 1.14017543])

##### Dizinin Toplamını Bulma 

In [32]:
summed = np.sum(vector1)

In [33]:
summed

3.5999999999999996

##### İki Vektörün Karşılıklı Elemanlarını Çarpıp Onların Toplamını Bulma (Skaler Çarpım) 

In [34]:
dotted = np.dot(vector1, vector2)

In [35]:
dotted

7.940000000000001

#####  Vektördeki, İstediğimiz Aralıktaki Sayıları Getirme

In [36]:
untamed = np.array([3,-21,4,-6,11,26,9,-3,12,-30,15])

+ -10'dan küçük olanları -10 olarak, 10'dan büyük olanları 10 olarak yazacaktır

In [37]:
clipped = np.clip(untamed, -10, 10)

In [38]:
clipped

array([  3, -10,   4,  -6,  10,  10,   9,  -3,  10, -10,  10])

##### np.minimum() Bütün değerler girilen sayıdan küçük olsun (Minimize et gibi bir anlamı var)

In [39]:
mini = np.minimum(untamed, 10)

In [40]:
mini

array([  3, -21,   4,  -6,  10,  10,   9,  -3,  10, -30,  10])

##### np.maximum() Bütün değerler girilen sayıdan büyük olsun (Maximize et gibi bir anlamı var)

In [41]:
maxi = np.maximum(untamed, -10)

In [42]:
maxi

array([  3, -10,   4,  -6,  11,  26,   9,  -3,  12, -10,  15])

##### Trigonometrik işlemler

In [43]:
vector3 = np.array([0,30,45,60,90])
vecsin = np.sin(vector3)
veccos = np.cos(vector3)
vectan = np.tan(vector3)

In [44]:
vecsin

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [45]:
veccos

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [46]:
vectan

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

##### Dizideki max ve min elemanları bulma 

In [47]:
new_array = np.array([123,43,5,5,3,5,435,4,34,3,-21])

In [48]:
np.max(new_array)

435

In [49]:
np.min(new_array)

-21

## Dizilerde basit işlemler  

In [50]:
bmi = np.array([21.851, 20.975, 21.750, 24.747, 21.441])
bmi

array([21.851, 20.975, 21.75 , 24.747, 21.441])

##### Listeden eleman çağırır gibi NumPy dizisinden de eleman çağırabiliriz 

In [51]:
bmi[1]

20.975

##### Boolean içeren bir diziyi tamamen sayılardan oluşan bir dizi üzerinden oluşturabiliriz 

In [52]:
bmi > 23

array([False, False, False,  True, False])

In [53]:
light = bmi < 22
light

array([ True,  True,  True, False,  True])

##### bmi adlı diziden light adlı şartı sağlayanları bir dizi haline getirdi 

In [54]:
bmi[light]

array([21.851, 20.975, 21.75 , 21.441])

##### True = 1 ve False = 0 olarak görülür

In [55]:
 np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

##### Dizilerin indexlerini çağırmak 

In [56]:
vector4 = np.array([100,123,324,111,110,115,146,127,139])
vector4_index = vector4[3:8]

In [57]:
vector4_index

array([111, 110, 115, 146, 127])

##### Dizideki elemanları küçükten büyüğe sıralamak ( np.sort() ) 

In [58]:
np.sort(vector4)

array([100, 110, 111, 115, 123, 127, 139, 146, 324])

## Boş Bir Diziyi Doldurmak

##### Parantez içine direkt olarak sayı girince girilen sayı kadar rasgele sayı atamak (parantez içine girilen sayı kadar atama yapar)

In [59]:
empty = np.empty(4)
empty

array([21.851, 20.975, 21.75 , 21.441])

##### İçi tamamen 0 (sıfır) ile dolu dizi oluşturmak

In [60]:
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

##### İçi tamamen 1 (bir) ile dolu dizi oluşturmak 

In [61]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

##### İçi tamamen istediğimiz sayı ile dolu dizi oluşturmak 

In [62]:
fulls = np.full(4, 3.14)
fulls

array([3.14, 3.14, 3.14, 3.14])

##### Verilen vektördeki eleman sayısı kadar elemanı olan dizi üretmek 

In [63]:
vector5 = np.array([4,1,2,5,5,6,1,3,4])
likes = np.ones_like(vector5)
likes

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [64]:
likes1 = np.zeros_like(vector5)
likes1

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
likes2 = np.full_like(vector5 , 27)
likes2

array([27, 27, 27, 27, 27, 27, 27, 27, 27])

##### np.linspace() ile belirli aralıklarla sayı içeren dizi oluşturulabilir

In [66]:
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Rasgele Sayı Üretmek

##### Normal dağılım olmayan rasgele sayıları üretmek 

In [67]:
random_uniform = np.random.uniform(size = 10)
random_uniform

array([0.69868605, 0.27908677, 0.3061818 , 0.98297604, 0.69915104,
       0.89710732, 0.95867   , 0.24416964, 0.86560094, 0.42753421])

##### Bir aralıkta Normal dağılım olmayan rasgele sayılar üretmek

In [68]:
random_uniform_1 = np.random.uniform(low = 1, high = 6, size = 10)
random_uniform_1

array([3.34637599, 1.99887685, 1.47718517, 5.02762249, 5.05117473,
       2.91048242, 3.79763342, 1.404026  , 4.6712008 , 5.19746707])

##### Normal dağılıma göre rasgele sayılar üretmek (Ortalama ,1.65 ve standart sapma, 0.80'dir) 

In [69]:
random_normal = np.random.normal(loc = 1.65, scale = 0.80, size = 10)
random_normal

array([1.31388055, 1.27349134, 3.16658295, 0.02832014, 2.17603371,
       3.22108172, 3.03188812, 0.45160299, 2.52710841, 2.09979105])

##### Tablo olarak sayı üretmek (2 Boyutlu) 

In [70]:
table = np.random.uniform(low = 1, high = 6, size = (10,5))
table

array([[5.27535914, 5.10172355, 4.65918072, 3.93334368, 5.28953603],
       [5.11891138, 1.14824322, 1.55159303, 1.84978187, 3.08255261],
       [1.29768892, 4.37410241, 5.21494626, 2.65739946, 4.69331392],
       [5.20270915, 3.36454205, 1.77770099, 2.94683541, 3.54004124],
       [2.26384144, 1.2904142 , 1.39847449, 4.66875363, 3.84548258],
       [2.74693723, 5.46301493, 5.13935245, 4.70764392, 3.4977432 ],
       [1.38230765, 4.78568213, 4.39173634, 2.47374619, 1.49195873],
       [2.87843028, 5.01610872, 4.99604148, 5.31168315, 1.96679427],
       [1.9689017 , 4.63165989, 1.14010747, 4.22750733, 5.4980795 ],
       [3.15296524, 3.22623292, 5.99484138, 2.86480225, 1.76626529]])

##### Tablo olarak sayı üretmek (3 Boyutlu) 

In [71]:
table1 = np.random.uniform(low = 1, high = 6, size = (10,5,2))
table1

array([[[1.50087735, 4.40941733],
        [1.25798812, 5.13032328],
        [5.34271495, 1.02063309],
        [4.22642071, 1.73436607],
        [5.56520191, 5.14033072]],

       [[5.08500291, 3.26111933],
        [4.11193274, 5.25662467],
        [3.43338642, 1.74804381],
        [5.93572044, 2.56269508],
        [5.37595085, 3.48162737]],

       [[4.24367924, 1.49495641],
        [4.06243984, 5.23554142],
        [5.22768279, 5.35118975],
        [1.09792143, 3.26338079],
        [3.43583612, 1.85572905]],

       [[4.34427045, 2.45745849],
        [1.31453218, 2.26938111],
        [4.58947489, 4.02955311],
        [5.22181287, 4.25376326],
        [5.97426439, 4.53706389]],

       [[1.05451422, 3.401515  ],
        [1.99410718, 1.28893858],
        [4.85027826, 5.65083801],
        [3.93652343, 4.61122897],
        [5.68434132, 1.16563999]],

       [[2.33761488, 1.28456856],
        [3.87848525, 2.82772766],
        [4.14233388, 2.26273088],
        [3.10495674, 2.83353688],
    

## 2 Boyutlu Dizilerde İşlemler

In [72]:
matrix = np.array([
    [11.0, 12.0, 13.0],
    [21.0, 22.0, 23.0],
    [31.0, 32.0, 33.0]
])

In [73]:
matrix

array([[11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [74]:
np_2d = np.array([
    [1.73, 1.68, 1.71, 1.89, 1.79],
    [65.4, 69.2, 63.6, 88.4, 68.7]
])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 69.2 , 63.6 , 88.4 , 68.7 ]])

##### ndarray.shape Matrisin kaç satır ve sütun olduğunu gösterir 

In [75]:
matrix.shape

(3, 3)

##### Aşağıdaki ifade 0'ıncı satırı verir 

In [76]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

##### Aşağıdaki 2 ifade de aynı şeyi verir 

In [77]:
np_2d[0][2]
np_2d[0,2]

1.71

##### Bütün satırların 1'den 3. indexe kadar olan elemanlarını verir 

In [78]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [69.2 , 63.6 ]])

##### 1. satırdan 2. satıra kadar ve 0. sütundan 2. sütuna kadar olan değerleri verir 

In [79]:
matrix[1:2, 0:2]

array([[21., 22.]])

##### 1. Satırdaki bütün elemanları verir

In [80]:
np_2d[1, :]

array([65.4, 69.2, 63.6, 88.4, 68.7])

##### İki matrisi dikey (vertically) olarak birleştirmek içi "np.vstack((.....))" kullanılır. 

In [81]:
vertical1 = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])

vertical2 = np.array([
    [41,42,43],
    [51,52,53]
])

+ Aşağıdaki işlem hata verecektir çünkü matrisler aynı boyutta değiller 

In [82]:
vertical1 + vertical2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

+ np.vstack((....)) tek bir parametre alır ve o da tuple şeklindedir. Eğer tuple şeklinde vermezsek aşağıdaki kod bloğunda olduğu gibi hata verir 

In [83]:
vertical3 = np.vstack(vertical1, vertical2)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

+ Doğrusu aşağıdaki gibidir

In [84]:
vertical4 = np.vstack((vertical1, vertical2))
vertical4

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53]])

##### İki matrisi yatay (horizontally) olarak birleştirmek için "np.hstack((.....))" kullanılır.

In [85]:
horizontal1 = np.array([
    [1,1],
    [2,2]
])

horizontal2 = np.array([
    [3,3],
    [4,4]
])

+ np.hstack((.....)) de 1 parametre alır ve o parametre tuple şeklinde olmalıdır

In [86]:
horizontal3 = np.hstack((horizontal1, horizontal2))
horizontal3

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## İstatistik ile İlgili Komutlar

In [87]:
stat_array = np.random.normal(loc = 10, scale = 3, size = 100) #Ortalaması 10, standart sapması 3 olan bir normal dağılımlı dizi
stat_array

array([12.52713608, 14.6941986 , 11.58131484,  9.80994811,  9.19921406,
       11.6876192 ,  7.27354376,  7.45350025,  9.95240145, 11.77874508,
       10.14591851, 15.04794252,  5.37089119, 12.87049228, 12.22791206,
       11.85841907,  5.0943633 , 12.26292574, 11.9514583 ,  9.15284009,
        8.19396774,  9.42780935,  9.34227988, 17.45966701, 10.80756737,
       10.72566811,  3.78624027,  9.81826969,  9.83568442, 12.74311051,
       10.08092069, 16.30399149,  8.34230029, 13.54812028, 13.24141614,
        8.62216898, 11.2125477 , 10.90468524, 15.22871657,  6.85094601,
        9.73892046, 10.60092995,  6.54144235, 11.63284731,  7.86558997,
       11.10265955, 10.91395577,  8.4616344 ,  6.84293409,  6.70022125,
       12.27716472, 10.23894185, 10.7041023 ,  9.47648065,  5.64266107,
        9.31597889, 17.70560581, 13.57166178, 11.67005759,  8.44914966,
        6.37350273, 10.29348563, 10.98086731,  4.5827044 ,  5.51241363,
        7.50686727,  9.37116186, 10.23553257, 10.63093491,  9.88

In [88]:
mean = np.mean(stat_array) # Ortalamayı hesaplar
mean

10.165276091102726

In [89]:
median = np.median(stat_array) # Medyanı hesaplar
median

10.19409045524564

In [90]:
sort_stat_array = np.sort(stat_array) # Dizideki elemanları küçükten büyüğe sıralar
sort_stat_array

array([ 3.78624027,  4.5827044 ,  5.0943633 ,  5.37089119,  5.42788775,
        5.51241363,  5.53132542,  5.64266107,  5.71318954,  6.32805508,
        6.37350273,  6.52142787,  6.54144235,  6.70022125,  6.84293409,
        6.85094601,  6.87136347,  6.9589609 ,  6.99247032,  7.071828  ,
        7.27354376,  7.30719032,  7.45350025,  7.50686727,  7.66172775,
        7.77645406,  7.86558997,  8.19396774,  8.34230029,  8.44914966,
        8.4616344 ,  8.62216898,  8.67166801,  8.97880563,  9.15284009,
        9.19921406,  9.31597889,  9.34227988,  9.37116186,  9.42780935,
        9.47648065,  9.73892046,  9.80994811,  9.81826969,  9.83568442,
        9.88694358,  9.95240145, 10.08092069, 10.14591851, 10.15264835,
       10.23553257, 10.23894185, 10.29348563, 10.34230233, 10.4946451 ,
       10.60092995, 10.63093491, 10.7041023 , 10.72566811, 10.80756737,
       10.90468524, 10.91395577, 10.98086731, 11.10265955, 11.2125477 ,
       11.26926766, 11.41555357, 11.52974358, 11.5746753 , 11.58

In [91]:
variance = np.var(stat_array) # Varyansı hesaplar
variance

9.157222538602356

In [93]:
standart_deviation = np.std(stat_array) # Standart sapmayı hesaplar
standart_deviation

3.0260903057579687

In [102]:
percentile1 = np.percentile(stat_array, 25) # Yüzdelikleri hesaplar (25, 50, 75) (1. , 2. , 3.)
percentile2 = np.percentile(stat_array, 50)
percentile3 = np.percentile(stat_array, 75)

In [103]:
print(percentile1)
print(percentile2)
print(percentile3)

7.747772484156274
10.19409045524564
11.881678877490982


In [106]:
quantile1 = np.quantile(stat_array, 0.25) # Çeyreklikleri hesaplar (0.25, 0.50, 0.75) (1. , 2. , 3.)
quantile2 = np.quantile(stat_array, 0.50)
quantile3 = np.quantile(stat_array, 0.75)

In [107]:
print(quantile1)
print(quantile2)
print(quantile3)

7.747772484156274
10.19409045524564
11.881678877490982


In [110]:
ptp = np.ptp(stat_array) # Range (Max - Min) hesaplar --> np.max(stat_array) - np.min(stat_array) ile aynı şeyi verir
ptp

13.919365542266808

In [113]:
array1 = np.random.normal(size = 25)
array2 = np.random.normal(size = 25)

In [114]:
array1

array([-0.21743606, -0.04352278,  0.08721328, -1.49012161,  1.15933957,
       -1.07903581,  1.22503888, -1.34778719,  1.13853912, -0.03421693,
        0.1076519 , -1.21530756, -2.47199359, -0.25461406, -1.83074544,
       -0.84552744,  0.19831884, -1.7203077 , -0.39895582,  1.19449347,
       -0.21165338, -0.61264227, -0.06174668,  0.95039265,  0.19761516])

In [115]:
array2

array([ 1.59570568,  1.71932536,  0.12228164,  0.41838079, -0.55406847,
        0.1578302 ,  0.35720606, -1.41724329,  0.04712075,  2.05538237,
       -0.24812855,  0.09560735, -0.44293843, -0.25355734, -1.00626535,
        0.86269966, -0.54031881,  0.21246435, -0.45384627, -0.04887088,
       -1.30471536,  1.16014841, -0.37666302, -1.1903837 ,  0.58873161])

In [119]:
corelation = np.corrcoef(x = array1, y = array2) # Korelasyon katsayısını hesaplar
corelation

array([[1.        , 0.05894895],
       [0.05894895, 1.        ]])

In [124]:
covariance = np.cov(m = array1, y = array2) # Kovaryansı hesaplar
covariance

array([[1.03273215, 0.05451879],
       [0.05451879, 0.82823332]])