# NumPy (Numeric Python) Nedir?

--> NumPy, Python'da bilimsel hesaplama için temel pakettir. Çok boyutlu bir dizi nesnesi, çeşitli türetilmiş nesneler (maskelenmiş diziler ve matrisler gibi) ve diziler üzerinde matematiksel, mantıksal, şekil işleme, sıralama, seçme, G/Ç dahil olmak üzere hızlı işlemler için çeşitli rutinler sağlayan bir Python kitaplığıdır. Ayrık Fourier dönüşümleri, temel doğrusal cebir, temel istatistiksel işlemler, rastgele simülasyon ve çok daha fazlasını yapmaya yarayan bir Python kitaplığıdır.

--> NumPy paketinin merkezinde "ndarray" nesnesi bulunur. Bu, performans için derlenmiş kodda gerçekleştirilen birçok işlemle birlikte, homojen veri türlerinin n boyutlu dizilerini kapsar. NumPy dizileri ile standart Python dizileri arasında birkaç önemli farklar vardır:

> NumPy dizileri, Python listelerinin (dinamik olarak büyüyebilen) aksine, oluşturulurken sabit bir boyuta sahiptir. Bir ndarray'in boyutunu değiştirmek, yeni bir dizi oluşturacak ve orijinali silecektir.

> NumPy dizisindeki öğelerin hepsinin aynı veri türünde olması gerekir ve bu nedenle bellekte aynı boyutta olacaktır. İstisna: bir (Python, NumPy dahil) nesne dizilerine sahip olabilir, böylece farklı büyüklükteki öğelerin dizilerine izin verilir.

> NumPy dizileri, çok sayıda veri üzerinde gelişmiş matematiksel ve diğer türdeki işlemleri kolaylaştırır. Tipik olarak, bu tür işlemler Python'un yerleşik dizileri kullanılarak mümkün olandan daha verimli ve daha az kodla yürütülür.

> Artan sayıda bilimsel ve matematiksel Python tabanlı paketler NumPy dizilerini kullanıyor; Bunlar tipik olarak Python dizisi girişini desteklese de, bu girişi işlemeden önce NumPy dizilerine dönüştürürler ve genellikle NumPy dizilerinin çıktısını alırlar. Başka bir deyişle, günümüzün bilimsel/matematiksel Python tabanlı yazılımlarının çoğunu (belki de çoğunu) verimli bir şekilde kullanmak için, yalnızca Python'un yerleşik dizi türlerini nasıl kullanacağınızı bilmek yetersizdir - ayrıca NumPy dizilerinin nasıl kullanılacağını da bilmek gerekir.

## NumPy Kütüphanesini Çağırma 

In [1]:
import numpy as np

## Dizi Oluşturma ve Dizilerde İşlemler 

###### Boş bir dizi oluşturma 

In [2]:
vectory_empty = np.array([]) 
print(vectory_empty)

[]


###### Dolu bir dizi oluşturma 

In [3]:
vectory_initialized = np.array([3,4,-5,6,8]) #NumPy ile dolu bir dizi oluşturduk
print(vectory_initialized)

[ 3  4 -5  6  8]


######  NumPy ile oluşturduğumuz dizi Python'un dizisi olmamasına rağmen Python'un dizisi gibi kullanılabiliyor.

In [4]:
for i in vectory_initialized:
    print(i)

3
4
-5
6
8


###### Diziye eleman ekleme  

In [5]:
vector = np.array([6,4,3,9,8])

In [6]:
vector

array([6, 4, 3, 9, 8])

In [7]:
np.append(vector,11)

array([ 6,  4,  3,  9,  8, 11])

###### Dizide istenilen indexe eleman ekleme 

In [8]:
np.insert(vector,2,5) #np.insert(işlem yapılacak dizi, eklenmek istenen index, eklenilecek değer)

array([6, 4, 5, 3, 9, 8])

###### Diziden eleman silme 

In [9]:
np.delete(vector,3) #np.delete(işlem yapılacak dizi, silinmek istenen index)

array([6, 4, 3, 8])

+ Dikkat edersek her bir işlem yeni bir dizi yaratıyor. Yani vector üzerine append, insert, delete işlemlerini uyguladığımızda Mevcut dizide işlem yapmak yerine yeni bir dizi oluşuturup yapıyor

In [10]:
vector 

array([6, 4, 3, 9, 8])

###### Dizinin Türünü Gösterme  

In [11]:
vector_1 = np.array([6,2,7,3,8])
print("Tür:", vector.dtype)

Tür: int32


##### Sadece 1 tanesinin float olması, dizinin türünü float olarak göstermesine neden olur

In [12]:
vector_2 = np.array([6,2,7.5,3,8]) 
print(f"Tür: {vector_2.dtype}")

Tür: float64


###### Diziyi 64 byte'a çevirme (Bu daha) 

In [13]:
vector_3 = np.array([6,2,7,8], np.int64)
print("Tür:", vector_3.dtype)

Tür: int64


###### Dizideki sayıları yuvarlama, np.around() ile yapılır. 

In [14]:
real = np.array([6.4325, 2.5436, 7.5436, 3.5432, 8.9543])

In [15]:
real

array([6.4325, 2.5436, 7.5436, 3.5432, 8.9543])

In [16]:
rounds = np.around(real)

In [17]:
rounds

array([6., 3., 8., 4., 9.])

###### Yuvarlama yapmamız dizinin türünü değiştirmez 

In [18]:
rounds.dtype 

dtype('float64')

###### decimals parametresi ile küsüratın kaç basamağını istediğimizi belirtebiliriz 

In [19]:
rounders = np.around(real, decimals = 2)

In [20]:
rounders

array([6.43, 2.54, 7.54, 3.54, 8.95])

###### Dizideki maksimum ve minimum değerleri bulma 

In [21]:
new_array = np.array([123,43,5,5,3,5,435,4,34,3,-21])

In [22]:
np.max(new_array)

435

In [23]:
np.min(new_array)

-21

##### Listeden eleman çağırır gibi NumPy dizisinden de eleman çağırabiliriz 

In [24]:
bmi = np.array([21.851, 20.975, 21.750, 24.747, 21.441])
bmi

array([21.851, 20.975, 21.75 , 24.747, 21.441])

In [25]:
bmi[1]

20.975

###### Boolean içeren bir diziyi tamamen sayılardan oluşan bir dizi üzerinden oluşturabiliriz 

In [26]:
bmi > 23

array([False, False, False,  True, False])

+ bmi adlı diziden light adlı şartı sağlayanları bir dizi haline getiriyoruz 

In [27]:
light = bmi < 22
light

array([ True,  True,  True, False,  True])

In [28]:
bmi[light]

array([21.851, 20.975, 21.75 , 21.441])

######  Vektördeki, İstediğimiz Aralıktaki Sayıları Getirme

In [29]:
untamed = np.array([3,-21,4,-6,11,26,9,-3,12,-30,15])

+ -10'dan küçük olanları -10 olarak, 10'dan büyük olanları 10 olarak yazacaktır

In [30]:
clipped = np.clip(untamed, -10, 10)

In [31]:
clipped

array([  3, -10,   4,  -6,  10,  10,   9,  -3,  10, -10,  10])

###### True = 1 ve False = 0 olarak görülür

In [32]:
 np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

###### Dizilerin indexlerini çağırmak 

In [33]:
vector4 = np.array([100,123,324,111,110,115,146,127,139])
vector4_index = vector4[3:8]

In [34]:
vector4_index

array([111, 110, 115, 146, 127])

###### Dizideki elemanları küçükten büyüğe sıralamak ( np.sort() ) 

In [35]:
np.sort(vector4)

array([100, 110, 111, 115, 123, 127, 139, 146, 324])

## Matematiksel İşlemler 

In [36]:
vector1 = np.array([1.1,1.2,1.3])
vector2 = np.array([2.1,2.2,2.3])

###### Toplama 

In [37]:
added = np.add(vector1, vector2)

In [38]:
added

array([3.2, 3.4, 3.6])

###### Çıkarma 

In [39]:
substracted = np.subtract(vector1, vector2)

In [40]:
substracted

array([-1., -1., -1.])

###### Çarpma 

In [41]:
multipled = np.multiply(vector1, vector2)

In [42]:
multipled

array([2.31, 2.64, 2.99])

###### Bölme 

In [43]:
divided = np.divide(vector1, vector2)

In [44]:
divided

array([0.52380952, 0.54545455, 0.56521739])

###### Kök Alma 

In [45]:
rooted = np.sqrt(vector1)

In [46]:
rooted

array([1.04880885, 1.09544512, 1.14017543])

###### Dizinin Toplamını Bulma 

In [47]:
summed = np.sum(vector1)

In [48]:
summed

3.5999999999999996

###### İki Vektörün Karşılıklı Elemanlarını Çarpıp Onların Toplamını Bulma (Skaler Çarpım) 

In [49]:
dotted = np.dot(vector1, vector2)

In [50]:
dotted

7.940000000000001

##### np.minimum() Bütün değerler girilen sayıdan küçük olsun (Minimize et gibi bir anlamı var)

In [51]:
mini = np.minimum(untamed, 10)

In [52]:
mini

array([  3, -21,   4,  -6,  10,  10,   9,  -3,  10, -30,  10])

##### np.maximum() Bütün değerler girilen sayıdan büyük olsun (Maximize et gibi bir anlamı var)

In [53]:
maxi = np.maximum(untamed, -10)

In [54]:
maxi

array([  3, -10,   4,  -6,  11,  26,   9,  -3,  12, -10,  15])

##### Trigonometrik işlemler

In [55]:
vector3 = np.array([0,30,45,60,90])
vecsin = np.sin(vector3)
veccos = np.cos(vector3)
vectan = np.tan(vector3)

In [56]:
vecsin

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [57]:
veccos

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [58]:
vectan

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

# !!!!!!

## Boş Bir Diziyi Doldurmak

###### Parantez içine direkt olarak sayı girince girilen sayı kadar rasgele sayı atamak (parantez içine girilen sayı kadar atama yapar)

In [59]:
empty = np.empty(4)
empty

array([6.4053312 , 1.61977519, 0.32004039, 1.99520041])

###### İçi tamamen 0 (sıfır) ile dolu dizi oluşturmak

In [60]:
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

###### İçi tamamen 1 (bir) ile dolu dizi oluşturmak 

In [61]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

###### İçi tamamen istediğimiz sayı ile dolu dizi oluşturmak 

In [62]:
fulls = np.full(4, 3.14)
fulls

array([3.14, 3.14, 3.14, 3.14])

###### Verilen vektördeki eleman sayısı kadar elemanı olan dizi üretmek 

In [63]:
vector5 = np.array([4,1,2,5,5,6,1,3,4])
likes = np.ones_like(vector5)
likes

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [64]:
likes1 = np.zeros_like(vector5)
likes1

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
likes2 = np.full_like(vector5 , 27)
likes2

array([27, 27, 27, 27, 27, 27, 27, 27, 27])

###### np.linspace() ile belirli aralıklarla sayı içeren dizi oluşturulabilir

In [66]:
np.linspace(0, 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Rasgele Sayı Üretmek

###### Normal dağılım olmayan rasgele sayıları üretmek 

In [67]:
random_uniform = np.random.uniform(size = 10)
random_uniform

array([0.2271367 , 0.17081541, 0.60347727, 0.2980972 , 0.11995641,
       0.4274201 , 0.42190093, 0.75296595, 0.08649498, 0.19364939])

###### Bir aralıkta Normal dağılım olmayan rasgele sayılar üretmek

In [68]:
random_uniform_1 = np.random.uniform(low = 1, high = 6, size = 10)
random_uniform_1

array([4.47930752, 1.2323247 , 1.23628499, 2.56322919, 3.75798674,
       5.41354867, 4.71378681, 3.02836208, 4.88265295, 3.47044448])

###### Normal dağılıma göre rasgele sayılar üretmek (Ortalama ,1.65 ve standart sapma, 0.80'dir) 

In [69]:
random_normal = np.random.normal(loc = 1.65, scale = 0.80, size = 10)
random_normal

array([1.12382487, 1.82937923, 1.91325308, 1.66660414, 3.03268953,
       1.87509412, 3.07032622, 1.35135455, 2.13545232, 1.37754942])

###### Tablo olarak sayı üretmek (2 Boyutlu) 

In [70]:
table = np.random.uniform(low = 1, high = 6, size = (10,5))
table

array([[2.5294053 , 2.68954013, 3.15214688, 2.1992701 , 1.95536948],
       [4.78221139, 2.37517874, 2.52477604, 2.70875587, 2.32386651],
       [1.48402268, 1.91669571, 1.39223502, 2.05719237, 1.07189308],
       [1.28035313, 1.22917363, 5.0775706 , 2.72335342, 5.94594979],
       [5.96632735, 3.48085165, 3.1248707 , 2.0609342 , 1.10746893],
       [2.92898195, 4.57108071, 4.8012248 , 1.24929504, 1.30077318],
       [5.89546408, 2.34027996, 3.80401421, 5.38353895, 4.13297742],
       [3.97563156, 4.52113928, 5.27188367, 4.43062555, 1.66479092],
       [3.61003481, 2.54596283, 5.58631719, 4.17295777, 2.56670401],
       [5.23471199, 2.46926987, 5.72339364, 2.40760955, 4.09894891]])

###### Tablo olarak sayı üretmek (3 Boyutlu) 

In [71]:
table1 = np.random.uniform(low = 1, high = 6, size = (10,5,2))
table1

array([[[2.4019585 , 2.86117247],
        [5.74071723, 4.41524564],
        [4.85221572, 2.3303903 ],
        [2.66753929, 4.9223736 ],
        [5.91731381, 3.58575243]],

       [[5.94699066, 2.35523377],
        [4.25196429, 2.47170784],
        [5.84967635, 4.41815192],
        [3.64906135, 5.5807845 ],
        [4.17931926, 3.49000244]],

       [[4.91811215, 2.57036587],
        [4.31432294, 4.00109608],
        [2.81341689, 1.33837907],
        [4.52021529, 4.20704198],
        [1.94173165, 1.65584501]],

       [[3.31273712, 3.58568129],
        [5.51458733, 5.318496  ],
        [4.15990783, 1.11153118],
        [5.58137598, 1.7200468 ],
        [4.61983081, 1.71011916]],

       [[2.55300407, 5.7615465 ],
        [2.21151842, 3.78537297],
        [5.33314805, 3.89569915],
        [5.6113766 , 3.46639687],
        [2.1101271 , 3.45149451]],

       [[3.60281349, 3.42082434],
        [2.68103723, 1.10310032],
        [5.06139912, 1.88993542],
        [4.05566826, 5.72322911],
    

## 2 Boyutlu Dizilerde İşlemler

In [72]:
matrix = np.array([
    [11.0, 12.0, 13.0],
    [21.0, 22.0, 23.0],
    [31.0, 32.0, 33.0]
])

In [73]:
matrix

array([[11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [74]:
np_2d = np.array([
    [1.73, 1.68, 1.71, 1.89, 1.79],
    [65.4, 69.2, 63.6, 88.4, 68.7]
])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 69.2 , 63.6 , 88.4 , 68.7 ]])

###### ndarray.shape Matrisin kaç satır ve sütun olduğunu gösterir 

In [75]:
matrix.shape

(3, 3)

###### Aşağıdaki ifade 0'ıncı satırı verir 

In [76]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

###### Aşağıdaki 2 ifade de aynı şeyi verir 

In [77]:
np_2d[0][2]
np_2d[0,2]

1.71

###### Bütün satırların 1'den 3. indexe kadar olan elemanlarını verir 

In [78]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [69.2 , 63.6 ]])

###### 1. satırdan 2. satıra kadar ve 0. sütundan 2. sütuna kadar olan değerleri verir 

In [79]:
matrix[1:2, 0:2]

array([[21., 22.]])

###### 1. Satırdaki bütün elemanları verir

In [80]:
np_2d[1, :]

array([65.4, 69.2, 63.6, 88.4, 68.7])

###### İki matrisi dikey (vertically) olarak birleştirmek içi "np.vstack((.....))" kullanılır. 

In [81]:
vertical1 = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])

vertical2 = np.array([
    [41,42,43],
    [51,52,53]
])

+ Aşağıdaki işlem hata verecektir çünkü matrisler aynı boyutta değiller 

In [82]:
vertical1 + vertical2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

+ np.vstack((....)) tek bir parametre alır ve o da tuple şeklindedir. Eğer tuple şeklinde vermezsek aşağıdaki kod bloğunda olduğu gibi hata verir 

In [83]:
vertical3 = np.vstack(vertical1, vertical2)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

+ Doğrusu aşağıdaki gibidir

In [84]:
vertical4 = np.vstack((vertical1, vertical2))
vertical4

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53]])

###### İki matrisi yatay (horizontally) olarak birleştirmek için "np.hstack((.....))" kullanılır.

In [85]:
horizontal1 = np.array([
    [1,1],
    [2,2]
])

horizontal2 = np.array([
    [3,3],
    [4,4]
])

+ np.hstack((.....)) de 1 parametre alır ve o parametre tuple şeklinde olmalıdır

In [86]:
horizontal3 = np.hstack((horizontal1, horizontal2))
horizontal3

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## İstatistik ile İlgili Komutlar

In [87]:
stat_array = np.random.normal(loc = 10, scale = 3, size = 100) #Ortalaması 10, standart sapması 3 olan bir normal dağılımlı dizi
stat_array

array([ 8.64276824, 11.38773917, 12.6141566 , 16.81463573, 12.8661481 ,
        9.39652627,  7.28649411, 15.95060815, 13.89885839, 16.0054609 ,
        9.72757762, 13.18401093, 14.19142515, 13.35155072, 10.71857201,
       12.01208424,  8.46367389,  7.97334094, 10.27410645, 12.57660604,
        9.65662432,  9.72042195,  7.98697912,  9.45161147, 12.49758915,
       14.71603527,  6.05132861, 11.52056651,  6.62614401,  8.65134082,
        9.65992193,  5.95264068, 10.84323082,  5.10511483, 12.0064331 ,
        9.29111011,  9.17795292,  8.09787118, 10.45198613, 12.52249168,
        7.8315872 , 12.99321436, 12.13847472,  7.1538216 , 10.03941763,
        6.40998339, 15.94282961, 14.5847147 ,  9.62679821,  9.73033519,
       14.22813139,  9.8295091 , 11.84162721,  8.84431708,  8.40064628,
        9.6004354 ,  7.63756325, 13.50289555,  9.66210876,  9.84324038,
        6.35393173,  8.78590381, 13.92766291, 12.40099606, 10.51907894,
       13.31591531, 14.18606854, 10.92844661, 10.3479008 , 12.12

###### Ortalamayı hesaplama 

In [88]:
mean = np.mean(stat_array) 
mean

10.491680459170828

###### Medyanı hesaplama 

In [89]:
median = np.median(stat_array) 
median

10.485532531861587

###### Dizideki elemanları küçükten büyüğe sıralama 

In [90]:
sort_stat_array = np.sort(stat_array) 
sort_stat_array

array([ 2.72161048,  3.63920404,  4.11130815,  4.6409564 ,  5.10511483,
        5.95264068,  6.05132861,  6.18272338,  6.35393173,  6.40998339,
        6.62614401,  7.01538562,  7.1538216 ,  7.28649411,  7.63756325,
        7.79521444,  7.8315872 ,  7.97334094,  7.98697912,  8.09787118,
        8.33464267,  8.40064628,  8.46367389,  8.64276824,  8.65134082,
        8.78590381,  8.84431708,  9.07423712,  9.17795292,  9.29111011,
        9.31188934,  9.31316492,  9.34656358,  9.39652627,  9.45161147,
        9.6004354 ,  9.62679821,  9.65662432,  9.65992193,  9.66210876,
        9.72042195,  9.72757762,  9.73033519,  9.80884079,  9.8295091 ,
        9.84324038, 10.03941763, 10.27410645, 10.3479008 , 10.45198613,
       10.51907894, 10.58200348, 10.71857201, 10.84323082, 10.92844661,
       10.98567419, 11.28225534, 11.38773917, 11.43148942, 11.52056651,
       11.68188171, 11.84162721, 11.84269802, 11.89103045, 12.0064331 ,
       12.01208424, 12.12575134, 12.13847472, 12.16946284, 12.40

###### Varyansı Hesaplama 

In [91]:
variance = np.var(stat_array) 
variance

8.080006778326121

###### Standart sapmayı hesaplama

In [92]:
standart_deviation = np.std(stat_array) 
standart_deviation

2.842535273013533

###### Yüzdelikleri hesaplama (25, 50, 75) (1. , 2. , 3.) 

In [93]:
percentile1 = np.percentile(stat_array, 25) 
percentile2 = np.percentile(stat_array, 50)
percentile3 = np.percentile(stat_array, 75)

In [94]:
print(percentile1)
print(percentile2)
print(percentile3)

8.752263063810164
10.485532531861587
12.585993682530805


###### Çeyreklikleri hesaplama (0.25, 0.50, 0.75) (1. , 2. , 3.) 

In [95]:
quantile1 = np.quantile(stat_array, 0.25) 
quantile2 = np.quantile(stat_array, 0.50)
quantile3 = np.quantile(stat_array, 0.75)

In [96]:
print(quantile1)
print(quantile2)
print(quantile3)

8.752263063810164
10.485532531861587
12.585993682530805


###### Range (Max - Min) hesaplama --> np.max(stat_array) - np.min(stat_array) ile aynı şeyi verir 

In [97]:
ptp = np.ptp(stat_array) 
ptp

14.093025243828073

###### Korelasyon katsayısını hesaplama 

In [98]:
array1 = np.random.normal(size = 25)
array2 = np.random.normal(size = 25)

In [99]:
array1

array([-0.42995059,  0.92021577,  1.240665  , -0.69334601, -0.20259938,
       -1.31033462, -0.18655838, -0.37130447, -0.10476839,  0.01963775,
        0.39874727,  1.00088044, -0.0211806 , -0.41875026,  1.24336603,
        1.19082765, -1.15225582,  0.78848305, -0.53453788, -0.90618338,
        1.79972414,  0.9907023 , -0.59911671,  0.18836233,  2.12589716])

In [100]:
array2

array([-2.07966564,  0.22385986, -1.05294318,  0.5792365 , -1.54128028,
       -0.05938528, -0.71897179,  1.78230937,  0.52381426, -0.8866895 ,
       -0.30442643,  1.07704722,  0.89083734, -0.87684916,  0.89604747,
       -0.70349867,  0.53127048, -0.63231221, -1.20254037,  2.10371146,
        1.45755592,  0.01814145,  0.66047345,  1.25819594,  0.59144424])

In [101]:
corelation = np.corrcoef(x = array1, y = array2) 
corelation

array([[1.        , 0.06798792],
       [0.06798792, 1.        ]])

###### Kovaryansı hesaplama 

In [102]:
covariance = np.cov(m = array1, y = array2) 
covariance

array([[0.85392773, 0.06768563],
       [0.06768563, 1.16066878]])